drop table dashboard;
drop table booking;
drop table room;
drop table hotel;
drop table userlist;


create table userlist(
    "U_ID" NUMBER, 
	"U_PWD" VARCHAR2(20 BYTE), 
	"U_NAME" VARCHAR2(20 BYTE), 
	"U_PHONE" VARCHAR2(20 BYTE), 
	"U_ADDRESS" VARCHAR2(50 BYTE), 
	"U_GRADE" NUMBER, 
	"U_EMAIL" VARCHAR2(20 BYTE), 
	 CONSTRAINT "USERLIST_PK" PRIMARY KEY ("U_ID")
    );

    
 CREATE TABLE HOTEL 
   ("H_ID" NUMBER, 
	"H_NAME" VARCHAR2(20 BYTE),
	"H_LOCATION" VARCHAR2(50 BYTE),
	"H_XPOINT" NUMBER,
	"H_YPOINT" NUMBER,
	"H_TEL" VARCHAR2(20 BYTE),
	"H_WIFI" NUMBER,
	"H_PARKING" NUMBER,
	"H_SWIMMING" NUMBER,
	"H_ROOMSERVICE" NUMBER,
	"H_BUS" NUMBER,
	"H_GRADE" NUMBER,
	"H_RATE" NUMBER,
	"H_IMG" VARCHAR2(50 BYTE),
	"H_DESC" VARCHAR2(1024 BYTE),
	 PRIMARY KEY ("H_ID")
	 );

	 
create table ROOM(
    "R_ID" number PRIMARY KEY,
    "R_NAME" VARCHAR2(20),
    "H_ID" NUMBER CONSTRAINT HID_FK REFERENCES HOTEL(H_ID),
    "R_NO" NUMBER,
    "R_PEOPLE" NUMBER,
    "R_TYPE" VARCHAR2(20),
    "R_COST" NUMBER,
    "R_ABLE" NUMBER,
    "R_B_COUNT" NUMBER,
    "R_IMG1" VARCHAR2(50),
    "R_IMG2" VARCHAR2(50),
    "R_IMG3" VARCHAR2(50)
    );

    
  CREATE TABLE "BOOKING" (
    "B_NO" NUMBER PRIMARY KEY,
    "B_U_ID" NUMBER CONSTRAINT BUID_FK REFERENCES USERLIST(U_ID), 
    "B_H_ID" NUMBER CONSTRAINT BHID_FK REFERENCES HOTEL(H_ID),
    "B_R_ID" NUMBER CONSTRAINT BRID_FK REFERENCES ROOM(R_ID), 
    "B_CHECKIN" DATE, 
    "B_CHECKOUT" DATE, 
    "B_PEOPLE" NUMBER, 
    "B_DATE" DATE, 
    "B_PLUS" NUMBER
     );
     

  CREATE TABLE "C##GYJ"."DASHBOARD" 
   (	"D_NO1" NUMBER, 
	"D_NO2" NUMBER, 
	"D_U_ID" NUMBER, 
	"D_U_NAME" VARCHAR2(20 BYTE), 
	"D_H_ID" NUMBER, 
	"D_R_ID" NUMBER, 
	"D_B_NO" NUMBER, 
	"D_REP_LEV" NUMBER, 
	"D_AVAILABLE" NUMBER, 
	"D_SPOINT" NUMBER, 
	"D_TITLE" VARCHAR2(50 BYTE), 
	"D_CONTENT" VARCHAR2(2048 BYTE), 
	"D_DATE" DATE, 
	"D_PASS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "DASHBOARD_PK" PRIMARY KEY ("D_NO1", "D_NO2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "DUID_FK" FOREIGN KEY ("D_U_ID")
	  REFERENCES "C##GYJ"."USERLIST" ("U_ID") ENABLE, 
	 CONSTRAINT "DHID_FK" FOREIGN KEY ("D_H_ID")
	  REFERENCES "C##GYJ"."HOTEL" ("H_ID") ENABLE, 
	 CONSTRAINT "DRID_FK" FOREIGN KEY ("D_R_ID")
	  REFERENCES "C##GYJ"."ROOM" ("R_ID") ENABLE, 
	 CONSTRAINT "DBNO_FK" FOREIGN KEY ("D_B_NO")
	  REFERENCES "C##GYJ"."BOOKING" ("B_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;